version: "3.7"
 
services:
  node:
    image: node-application:3.0.0
    environment:
      - SHELL=/bin/bash
      - MONGO_TEST_URL=mongodb://admin:mindgrep@mongodb1,mongodb2,mongodb3:27017/test
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - mongodb1
 
  mongodb1:
    image: mongo:5.0
    volumes:
      - mongodb1-prod-data:/data/db
      - ./scripts:/scripts
    ports:
      - 27017:27017
    depends_on:
      - mongodb2
      - mongodb3
    restart: always
    command: 'bash -c "/scripts/mongodb_init.sh"'
 
  mongodb2:
    image: mongo:5.0
    volumes:
      - mongodb2-prod-data:/data/db
      - ./scripts:/scripts
    ports:
      - 27018:27017
    restart: always
    command: 'bash -c "/scripts/mongodb_init.sh"'
 
  mongodb3:
    image: mongo:5.0
    volumes:
      - mongodb3-prod-data:/data/db
      - ./scripts:/scripts
    ports:
      - 27019:27017
    restart: always
    command: 'bash -c "/scripts/mongodb_init.sh"'
 
 
volumes:
  mongodb1-prod-data:
  mongodb2-prod-data:
  mongodb3-prod-data: